### ISSUE TITLE
Seems to be unhelpful

### ISSUE THREAD

**Issue by BigBobDalton** [Vertanzil/Block-Youtube-Ads#1]
Ive used this file on AdGuardHome but it does not appear to work very well.  Most Youtube videos have ads and  multiple ads so that I have to believe that this is incompatible with AdGuard

**Comment by Vertanzil** [comment]
I don't know how AdGuard works. I mainly use this for my own instance of Pi-hole and wanted somewhere to keep it.

Perhaps look into that or another way to block Youtube ads, I have used AdblockPlus in the past that worked pretty well.
